# Generated by Django 5.0.7 on 2025-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
